# Generated by Django 3.0.2 on 2020-01-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_image',
        ),
        migrations.AddField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(null=True, upload_to='album-cover'),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='song',
            name='song_cover',
            field=models.ImageField(null=True, upload_to='song-cover'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(upload_to='songs-file'),
        ),
    ]
