# Generated by Django 3.0.2 on 2020-01-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200103_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(null=True, upload_to='artist-image'),
        ),
    ]
