# Generated by Django 3.0.2 on 2020-01-03 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_artist_artist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_artist',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
