# Generated by Django 3.0.2 on 2020-01-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_album_album_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_rating',
            field=models.IntegerField(default=0),
        ),
    ]
