# Generated by Django 3.0.2 on 2020-01-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_album_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
