# Generated by Django 3.0.2 on 2020-01-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_rating',
        ),
        migrations.AddField(
            model_name='album',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='album',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
